---
# tasks file for role_upgrade_check
- block:
  - import_tasks: obtain_openshift_auth.yml
    tags:
      - obtain_openshift_auth

  - import_tasks: verify_upgrade_path.yml
    tags:
      - always
      - verify_upgrade_path 
  
  - import_tasks: verify_openshift_components.yml
    tags:
      - verify_openshift_components

  - import_tasks: verify_openshift_mcp_and_nodes.yml
    tags:
      - verify_openshift_mcp_and_nodes
  
  - import_tasks: verify_prometheus_alerts.yml
    tags:
      - verify_prometheus_alerts
  
  - import_tasks: verify_resources_consumption.yml
    tags:
      - verify_resources_consumption
  
  - import_tasks: verify_api_deprecation.yml
    tags:
      - verify_api_deprecation
  
  - import_tasks: verify_etcd_performance.yml
    tags:
      - verify_etcd_performance
  
  - import_tasks: revoke_openshift_auth.yml
    tags:
      - always
      - revoke_openshift_auth
      
  module_defaults:
    - redhat.openshift.openshift_auth:
        host: "{{ openshift_upgrade_checks_api_url }}"
        validate_certs: "{{ openshift_upgrade_checks_validate_certs }}"
    - kubernetes.core.k8s_info:
        host: "{{ openshift_upgrade_checks_api_url }}"
        validate_certs: "{{ openshift_upgrade_checks_validate_certs }}"
    - kubernetes.core.k8s:
        host: "{{ openshift_upgrade_checks_api_url }}"
        validate_certs: "{{ openshift_upgrade_checks_validate_certs }}"
    - kubernetes.core.k8s_exec:
        host: "{{ openshift_upgrade_checks_api_url }}"
        validate_certs: "{{ openshift_upgrade_checks_validate_certs }}"

